import { MenuProps } from 'antd';

export const dataCustomer = [
  {
    id: 1,
    image: 'https://randomuser.me/api/portraits/men/30.jpg',
    name: 'Elizabeth Young',
    email: 'v.mdotmx@internet.com',
    phone: '301746178869',
    date: '2012-08-06',
    organization: 'Visionary Labs',
    tags: 2,
    lastUpdated: '3 weeks ago',
  },
  {
    id: 2,
    image: 'https://randomuser.me/api/portraits/men/10.jpg',
    name: 'Brenda Rodriguez',
    email: 'h.nzbum@internet.com',
    phone: '44010966387',
    date: '2022-06-19',
    organization: 'PixelSoft Corporation',
    tags: 1,
    lastUpdated: '5 days ago',
  },
  {
    id: 3,
    image: 'https://randomuser.me/api/portraits/men/8.jpg',
    name: 'Cynthia Lewis',
    email: 't.psm@internet.com',
    phone: '13856681372',
    date: '1987-05-08',
    organization: 'Tech Innovators Inc.',
    tags: 1,
    lastUpdated: '1 month ago',
  },
  {
    id: 4,
    image: 'https://randomuser.me/api/portraits/men/6.jpg',
    name: 'Mary Thompson',
    email: 'v.bqrrovrhp@internet.com',
    phone: '910846507156',
    date: '2006-11-29',
    organization: 'Visionary Labs',
    tags: 3,
    lastUpdated: '6 days ago',
  },
  {
    id: 5,
    image: 'https://randomuser.me/api/portraits/men/39.jpg',
    name: 'Charles Hernandez',
    email: 'm.arrt@internet.com',
    phone: '689143327383',
    date: '2011-02-04',
    organization: 'PixelSoft Corporation',
    tags: 3,
    lastUpdated: '1 month ago',
  },
  {
    id: 6,
    image: 'https://randomuser.me/api/portraits/men/99.jpg',
    name: 'John Taylor',
    email: 'l.hkzt@internet.com',
    phone: '96670431346',
    date: '1970-07-16',
    organization: 'NextGen Technologies',
    tags: 1,
    lastUpdated: '1 month ago',
  },
  {
    id: 7,
    image: 'https://randomuser.me/api/portraits/men/9.jpg',
    name: 'Brenda Thomas',
    email: 'f.nujlaswkf@internet.com',
    phone: '84740800907',
    date: '1975-05-30',
    organization: 'Quantum Enterprises',
    tags: 3,
    lastUpdated: '5 days ago',
  },
  {
    id: 8,
    image: 'https://randomuser.me/api/portraits/men/69.jpg',
    name: 'Melissa Hall',
    email: 'd.hlkstf@internet.com',
    phone: '16399954363',
    date: '1973-03-12',
    organization: 'Visionary Labs',
    tags: 1,
    lastUpdated: '4 weeks ago',
  },
  {
    id: 9,
    image: 'https://randomuser.me/api/portraits/men/56.jpg',
    name: 'Steven Jackson',
    email: 'r.qmkgv@internet.com',
    phone: '498053938572',
    date: '1996-08-18',
    organization: 'Cyberdyne Systems',
    tags: 1,
    lastUpdated: '4 weeks ago',
  },
  {
    id: 10,
    image: 'https://randomuser.me/api/portraits/men/6.jpg',
    name: 'Kimberly Rodriguez',
    email: 'y.dcz@internet.com',
    phone: '158978339848',
    date: '1992-08-14',
    organization: 'Vertex Innovations',
    tags: 1,
    lastUpdated: '4 weeks ago',
  },
  {
    id: 11,
    image: 'https://randomuser.me/api/portraits/men/59.jpg',
    name: 'Jose Williams',
    email: 'f.ukjjlhpa@internet.com',
    phone: '661080471780',
    date: '1971-02-09',
    organization: 'Cyberdyne Systems',
    tags: 2,
    lastUpdated: '4 weeks ago',
  },
  {
    id: 12,
    image: 'https://randomuser.me/api/portraits/men/97.jpg',
    name: 'Frank Lewis',
    email: 't.tynnixwoxj@internet.com',
    phone: '49156881375',
    date: '2017-01-17',
    organization: 'Stratosphere Networks',
    tags: 3,
    lastUpdated: '2 days ago',
  },
  {
    id: 13,
    image: 'https://randomuser.me/api/portraits/men/55.jpg',
    name: 'Edward Clark',
    email: 'b.xylgen@internet.com',
    phone: '96794248803',
    date: '2019-12-11',
    organization: 'PixelSoft Corporation',
    tags: 1,
    lastUpdated: '3 weeks ago',
  },
  {
    id: 14,
    image: 'https://randomuser.me/api/portraits/men/87.jpg',
    name: 'Kenneth Lopez',
    email: 'j.pqspnyuh@internet.com',
    phone: '11148795980',
    date: '1977-02-01',
    organization: 'Stratosphere Networks',
    tags: 2,
    lastUpdated: '1 month ago',
  },
  {
    id: 15,
    image: 'https://randomuser.me/api/portraits/men/25.jpg',
    name: 'Matthew Lee',
    email: 't.kew@internet.com',
    phone: '949447123363',
    date: '2005-10-27',
    organization: 'Global Solutions Ltd.',
    tags: 1,
    lastUpdated: '2 days ago',
  },
  {
    id: 16,
    image: 'https://randomuser.me/api/portraits/men/39.jpg',
    name: 'Larry Martinez',
    email: 'w.inbljeyhvv@internet.com',
    phone: '80859195928',
    date: '2002-05-16',
    organization: 'Cyberdyne Systems',
    tags: 1,
    lastUpdated: '5 days ago',
  },
  {
    id: 17,
    image: 'https://randomuser.me/api/portraits/men/65.jpg',
    name: 'Barbara Garcia',
    email: 'd.msez@internet.com',
    phone: '803799958163',
    date: '2017-10-16',
    organization: 'NextGen Technologies',
    tags: 3,
    lastUpdated: '2 days ago',
  },
  {
    id: 18,
    image: 'https://randomuser.me/api/portraits/men/33.jpg',
    name: 'Barbara Anderson',
    email: 'v.jwdil@internet.com',
    phone: '670637447318',
    date: '2015-03-17',
    organization: 'Visionary Labs',
    tags: 1,
    lastUpdated: '5 days ago',
  },
  {
    id: 19,
    image: 'https://randomuser.me/api/portraits/men/81.jpg',
    name: 'Barbara Davis',
    email: 'm.uajqg@internet.com',
    phone: '23746983589',
    date: '1998-09-05',
    organization: 'Quantum Enterprises',
    tags: 2,
    lastUpdated: '1 week ago',
  },
  {
    id: 20,
    image: 'https://randomuser.me/api/portraits/men/91.jpg',
    name: 'Ronald Taylor',
    email: 'l.vju@internet.com',
    phone: '40485684623',
    date: '1975-12-26',
    organization: 'Visionary Labs',
    tags: 3,
    lastUpdated: '5 days ago',
  },
  {
    id: 21,
    image: 'https://randomuser.me/api/portraits/men/66.jpg',
    name: 'Linda Thompson',
    email: 's.skjwdm@internet.com',
    phone: '58889116488',
    date: '1994-07-31',
    organization: 'Cyberdyne Systems',
    tags: 1,
    lastUpdated: '2 days ago',
  },
  {
    id: 22,
    image: 'https://randomuser.me/api/portraits/men/57.jpg',
    name: 'Deborah Smith',
    email: 'f.ogxaqebct@internet.com',
    phone: '99099659378',
    date: '1985-03-21',
    organization: 'Vertex Innovations',
    tags: 3,
    lastUpdated: '1 week ago',
  },
  {
    id: 23,
    image: 'https://randomuser.me/api/portraits/men/52.jpg',
    name: 'Jason Jackson',
    email: 'i.smhjsrzoc@internet.com',
    phone: '19526558656',
    date: '1993-08-08',
    organization: 'Global Solutions Ltd.',
    tags: 3,
    lastUpdated: '1 month ago',
  },
  {
    id: 24,
    image: 'https://randomuser.me/api/portraits/men/6.jpg',
    name: 'Robert Martin',
    email: 'f.ikj@internet.com',
    phone: '63242167326',
    date: '1985-08-02',
    organization: 'Tech Innovators Inc.',
    tags: 2,
    lastUpdated: '3 weeks ago',
  },
  {
    id: 25,
    image: 'https://randomuser.me/api/portraits/men/75.jpg',
    name: 'Sharon Harris',
    email: 'c.iauq@internet.com',
    phone: '75517126702',
    date: '1992-06-24',
    organization: 'Stratosphere Networks',
    tags: 2,
    lastUpdated: '4 weeks ago',
  },
  {
    id: 26,
    image: 'https://randomuser.me/api/portraits/men/56.jpg',
    name: 'Kevin Lopez',
    email: 'i.ltjovuq@internet.com',
    phone: '84663984343',
    date: '2024-06-06',
    organization: 'Apollo Digital Solutions',
    tags: 3,
    lastUpdated: '1 week ago',
  },
  {
    id: 27,
    image: 'https://randomuser.me/api/portraits/men/42.jpg',
    name: 'Larry Perez',
    email: 'e.rhsxf@internet.com',
    phone: '702630829741',
    date: '1983-07-05',
    organization: 'NextGen Technologies',
    tags: 2,
    lastUpdated: '2 days ago',
  },
  {
    id: 28,
    image: 'https://randomuser.me/api/portraits/men/12.jpg',
    name: 'Jessica Gonzalez',
    email: 'p.lqlpu@internet.com',
    phone: '58870125806',
    date: '1993-10-22',
    organization: 'Tech Innovators Inc.',
    tags: 3,
    lastUpdated: '4 weeks ago',
  },
  {
    id: 29,
    image: 'https://randomuser.me/api/portraits/men/14.jpg',
    name: 'Barbara Garcia',
    email: 'l.beyoht@internet.com',
    phone: '67024795447',
    date: '2019-10-31',
    organization: 'NextGen Technologies',
    tags: 1,
    lastUpdated: '4 weeks ago',
  },
  {
    id: 30,
    image: 'https://randomuser.me/api/portraits/men/43.jpg',
    name: 'Maria Thomas',
    email: 'h.bscf@internet.com',
    phone: '96681493903',
    date: '2010-06-08',
    organization: 'PixelSoft Corporation',
    tags: 1,
    lastUpdated: '1 week ago',
  },
  {
    id: 31,
    image: 'https://randomuser.me/api/portraits/men/32.jpg',
    name: 'Daniel Davis',
    email: 't.rixpmts@internet.com',
    phone: '495652868704',
    date: '1990-12-24',
    organization: 'Cyberdyne Systems',
    tags: 1,
    lastUpdated: '2 months ago',
  },
  {
    id: 32,
    image: 'https://randomuser.me/api/portraits/men/8.jpg',
    name: 'Jose Thompson',
    email: 's.iwsaf@internet.com',
    phone: '92205220064',
    date: '1970-05-07',
    organization: 'Tech Innovators Inc.',
    tags: 3,
    lastUpdated: '4 weeks ago',
  },
  {
    id: 33,
    image: 'https://randomuser.me/api/portraits/men/11.jpg',
    name: 'Edward Perez',
    email: 'd.yepnwtf@internet.com',
    phone: '16766606862',
    date: '2019-07-01',
    organization: 'Cyberdyne Systems',
    tags: 3,
    lastUpdated: '1 month ago',
  },
  {
    id: 34,
    image: 'https://randomuser.me/api/portraits/men/100.jpg',
    name: 'Charles Martin',
    email: 'h.xqyjjza@internet.com',
    phone: '90609458737',
    date: '2022-09-10',
    organization: 'Vertex Innovations',
    tags: 2,
    lastUpdated: '2 months ago',
  },
  {
    id: 35,
    image: 'https://randomuser.me/api/portraits/men/9.jpg',
    name: 'Jennifer Jones',
    email: 'l.vmeszwkiu@internet.com',
    phone: '516998950932',
    date: '1970-04-11',
    organization: 'NextGen Technologies',
    tags: 3,
    lastUpdated: '5 days ago',
  },
  {
    id: 36,
    image: 'https://randomuser.me/api/portraits/men/55.jpg',
    name: 'Eric Thomas',
    email: 'r.pfpskf@internet.com',
    phone: '586297462431',
    date: '1993-09-07',
    organization: 'Global Solutions Ltd.',
    tags: 2,
    lastUpdated: '4 weeks ago',
  },
  {
    id: 37,
    image: 'https://randomuser.me/api/portraits/men/88.jpg',
    name: 'Paul Walker',
    email: 'j.mvpi@internet.com',
    phone: '813025581269',
    date: '2007-07-28',
    organization: 'Global Solutions Ltd.',
    tags: 3,
    lastUpdated: '2 months ago',
  },
  {
    id: 38,
    image: 'https://randomuser.me/api/portraits/men/9.jpg',
    name: 'Nancy Garcia',
    email: 'r.fgv@internet.com',
    phone: '73531611000',
    date: '2000-06-19',
    organization: 'Visionary Labs',
    tags: 1,
    lastUpdated: '2 months ago',
  },
  {
    id: 39,
    image: 'https://randomuser.me/api/portraits/men/52.jpg',
    name: 'Kevin Hall',
    email: 'x.uoddzwskn@internet.com',
    phone: '942913586477',
    date: '2020-03-21',
    organization: 'NextGen Technologies',
    tags: 2,
    lastUpdated: '1 week ago',
  },
  {
    id: 40,
    image: 'https://randomuser.me/api/portraits/men/36.jpg',
    name: 'Frank Thompson',
    email: 'g.qayy@internet.com',
    phone: '24441873365',
    date: '1973-03-27',
    organization: 'Tech Innovators Inc.',
    tags: 2,
    lastUpdated: '1 week ago',
  },
  {
    id: 41,
    image: 'https://randomuser.me/api/portraits/men/41.jpg',
    name: 'Shirley Martin',
    email: 'c.rord@internet.com',
    phone: '86638623341',
    date: '2011-10-05',
    organization: 'PixelSoft Corporation',
    tags: 3,
    lastUpdated: '4 weeks ago',
  },
  {
    id: 42,
    image: 'https://randomuser.me/api/portraits/men/34.jpg',
    name: 'Kenneth Williams',
    email: 'i.qvxkcd@internet.com',
    phone: '79602871582',
    date: '2021-10-11',
    organization: 'Visionary Labs',
    tags: 1,
    lastUpdated: '1 week ago',
  },
  {
    id: 43,
    image: 'https://randomuser.me/api/portraits/men/95.jpg',
    name: 'Kevin Brown',
    email: 'v.ryrrclhy@internet.com',
    phone: '853394899948',
    date: '2017-07-10',
    organization: 'Vertex Innovations',
    tags: 1,
    lastUpdated: '1 week ago',
  },
  {
    id: 44,
    image: 'https://randomuser.me/api/portraits/men/69.jpg',
    name: 'Frank Jackson',
    email: 'b.jkyenx@internet.com',
    phone: '47503612581',
    date: '1988-06-25',
    organization: 'Cyberdyne Systems',
    tags: 3,
    lastUpdated: '1 month ago',
  },
  {
    id: 45,
    image: 'https://randomuser.me/api/portraits/men/46.jpg',
    name: 'Patricia White',
    email: 'j.qncqki@internet.com',
    phone: '598600409059',
    date: '2010-10-13',
    organization: 'Apollo Digital Solutions',
    tags: 1,
    lastUpdated: '2 months ago',
  },
  {
    id: 46,
    image: 'https://randomuser.me/api/portraits/men/74.jpg',
    name: 'Linda Walker',
    email: 'j.kcwcsom@internet.com',
    phone: '92897907567',
    date: '1990-04-09',
    organization: 'Stratosphere Networks',
    tags: 3,
    lastUpdated: '1 week ago',
  },
  {
    id: 47,
    image: 'https://randomuser.me/api/portraits/men/94.jpg',
    name: 'Joseph Rodriguez',
    email: 'h.hlncekqd@internet.com',
    phone: '923902869072',
    date: '1987-12-24',
    organization: 'Visionary Labs',
    tags: 1,
    lastUpdated: '5 days ago',
  },
  {
    id: 48,
    image: 'https://randomuser.me/api/portraits/men/94.jpg',
    name: 'John Thompson',
    email: 'n.wutgx@internet.com',
    phone: '34504324488',
    date: '1998-07-15',
    organization: 'Vertex Innovations',
    tags: 3,
    lastUpdated: '4 weeks ago',
  },
  {
    id: 49,
    image: 'https://randomuser.me/api/portraits/men/61.jpg',
    name: 'James Garcia',
    email: 'j.toizybhvj@internet.com',
    phone: '658495049844',
    date: '2013-09-28',
    organization: 'NextGen Technologies',
    tags: 1,
    lastUpdated: '1 week ago',
  },
  {
    id: 50,
    image: 'https://randomuser.me/api/portraits/men/14.jpg',
    name: 'Frank Gonzalez',
    email: 'u.iqferdq@internet.com',
    phone: '31047353296',
    date: '2017-05-13',
    organization: 'Cyberdyne Systems',
    tags: 2,
    lastUpdated: '3 weeks ago',
  },
  {
    id: 51,
    image: 'https://randomuser.me/api/portraits/men/82.jpg',
    name: 'Anna Williams',
    email: 'a.gamsafxt@internet.com',
    phone: '83639222057',
    date: '1973-12-27',
    organization: 'Global Solutions Ltd.',
    tags: 2,
    lastUpdated: '5 days ago',
  },
  {
    id: 52,
    image: 'https://randomuser.me/api/portraits/men/96.jpg',
    name: 'Margaret Thomas',
    email: 'c.jkehnc@internet.com',
    phone: '886180922417',
    date: '1973-11-24',
    organization: 'Visionary Labs',
    tags: 1,
    lastUpdated: '3 weeks ago',
  },
  {
    id: 53,
    image: 'https://randomuser.me/api/portraits/men/82.jpg',
    name: 'Amy Williams',
    email: 'h.revsyd@internet.com',
    phone: '82600565256',
    date: '1983-08-12',
    organization: 'Vertex Innovations',
    tags: 3,
    lastUpdated: '4 weeks ago',
  },
  {
    id: 54,
    image: 'https://randomuser.me/api/portraits/men/69.jpg',
    name: 'Larry Johnson',
    email: 't.bwuizm@internet.com',
    phone: '104017362308',
    date: '2020-02-01',
    organization: 'Stratosphere Networks',
    tags: 3,
    lastUpdated: '2 months ago',
  },
  {
    id: 55,
    image: 'https://randomuser.me/api/portraits/men/63.jpg',
    name: 'Michelle Thompson',
    email: 'q.gyvovkw@internet.com',
    phone: '308274786814',
    date: '2017-03-27',
    organization: 'PixelSoft Corporation',
    tags: 3,
    lastUpdated: '4 weeks ago',
  },
  {
    id: 56,
    image: 'https://randomuser.me/api/portraits/men/9.jpg',
    name: 'Margaret Williams',
    email: 'g.rmluygkc@internet.com',
    phone: '12969682741',
    date: '2003-06-22',
    organization: 'Tech Innovators Inc.',
    tags: 1,
    lastUpdated: '6 days ago',
  },
  {
    id: 57,
    image: 'https://randomuser.me/api/portraits/men/37.jpg',
    name: 'William Anderson',
    email: 'e.abrm@internet.com',
    phone: '435977851636',
    date: '2008-02-24',
    organization: 'Cyberdyne Systems',
    tags: 1,
    lastUpdated: '4 weeks ago',
  },
  {
    id: 58,
    image: 'https://randomuser.me/api/portraits/men/23.jpg',
    name: 'Sarah Jackson',
    email: 'y.dycwl@internet.com',
    phone: '369089923265',
    date: '2016-03-23',
    organization: 'Cyberdyne Systems',
    tags: 2,
    lastUpdated: '5 days ago',
  },
  {
    id: 59,
    image: 'https://randomuser.me/api/portraits/men/75.jpg',
    name: 'Joseph Moore',
    email: 'p.sflokfouc@internet.com',
    phone: '196264670104',
    date: '1971-12-11',
    organization: 'PixelSoft Corporation',
    tags: 3,
    lastUpdated: '2 days ago',
  },
  {
    id: 60,
    image: 'https://randomuser.me/api/portraits/men/61.jpg',
    name: 'Shirley Thomas',
    email: 'v.tmgkvuwqw@internet.com',
    phone: '195800283806',
    date: '1992-06-18',
    organization: 'Global Solutions Ltd.',
    tags: 3,
    lastUpdated: '4 weeks ago',
  },
  {
    id: 61,
    image: 'https://randomuser.me/api/portraits/men/90.jpg',
    name: 'Jessica Martinez',
    email: 'j.pgcqjvl@internet.com',
    phone: '32536949254',
    date: '2023-03-20',
    organization: 'Global Solutions Ltd.',
    tags: 1,
    lastUpdated: '1 week ago',
  },
  {
    id: 62,
    image: 'https://randomuser.me/api/portraits/men/57.jpg',
    name: 'Jessica Miller',
    email: 'b.coha@internet.com',
    phone: '81681505012',
    date: '1987-05-24',
    organization: 'Apollo Digital Solutions',
    tags: 2,
    lastUpdated: '2 days ago',
  },
  {
    id: 63,
    image: 'https://randomuser.me/api/portraits/men/52.jpg',
    name: 'Kimberly Hernandez',
    email: 'e.jkpg@internet.com',
    phone: '95329934270',
    date: '2010-12-24',
    organization: 'Apollo Digital Solutions',
    tags: 2,
    lastUpdated: '1 week ago',
  },
  {
    id: 64,
    image: 'https://randomuser.me/api/portraits/men/78.jpg',
    name: 'Jeffrey Johnson',
    email: 'w.puhjztc@internet.com',
    phone: '916061368025',
    date: '1978-02-18',
    organization: 'Tech Innovators Inc.',
    tags: 3,
    lastUpdated: '4 weeks ago',
  },
  {
    id: 65,
    image: 'https://randomuser.me/api/portraits/men/51.jpg',
    name: 'Karen Hall',
    email: 'o.feqedbfq@internet.com',
    phone: '982973059150',
    date: '2018-02-16',
    organization: 'Apollo Digital Solutions',
    tags: 2,
    lastUpdated: '6 days ago',
  },
  {
    id: 66,
    image: 'https://randomuser.me/api/portraits/men/55.jpg',
    name: 'Anthony Miller',
    email: 'd.gfkdiohp@internet.com',
    phone: '11894860519',
    date: '1972-09-18',
    organization: 'Tech Innovators Inc.',
    tags: 2,
    lastUpdated: '1 month ago',
  },
  {
    id: 67,
    image: 'https://randomuser.me/api/portraits/men/34.jpg',
    name: 'Betty Clark',
    email: 'z.mwjqwunt@internet.com',
    phone: '963369789149',
    date: '2016-11-18',
    organization: 'Tech Innovators Inc.',
    tags: 3,
    lastUpdated: '1 week ago',
  },
  {
    id: 68,
    image: 'https://randomuser.me/api/portraits/men/45.jpg',
    name: 'Mary White',
    email: 's.dsib@internet.com',
    phone: '29151298264',
    date: '1978-01-23',
    organization: 'NextGen Technologies',
    tags: 1,
    lastUpdated: '3 weeks ago',
  },
  {
    id: 69,
    image: 'https://randomuser.me/api/portraits/men/23.jpg',
    name: 'William Hall',
    email: 'f.ihrihjo@internet.com',
    phone: '74957592152',
    date: '2019-08-27',
    organization: 'PixelSoft Corporation',
    tags: 2,
    lastUpdated: '2 months ago',
  },
  {
    id: 70,
    image: 'https://randomuser.me/api/portraits/men/74.jpg',
    name: 'George Martinez',
    email: 'j.sjjknvar@internet.com',
    phone: '484969183519',
    date: '1991-12-09',
    organization: 'Global Solutions Ltd.',
    tags: 1,
    lastUpdated: '1 week ago',
  },
  {
    id: 71,
    image: 'https://randomuser.me/api/portraits/men/12.jpg',
    name: 'Lisa Harris',
    email: 'n.nhhwrgo@internet.com',
    phone: '408366800536',
    date: '2002-04-07',
    organization: 'NextGen Technologies',
    tags: 3,
    lastUpdated: '6 days ago',
  },
  {
    id: 72,
    image: 'https://randomuser.me/api/portraits/men/92.jpg',
    name: 'Lisa Jackson',
    email: 'y.hkk@internet.com',
    phone: '369552166094',
    date: '1972-08-01',
    organization: 'Tech Innovators Inc.',
    tags: 2,
    lastUpdated: '3 weeks ago',
  },
  {
    id: 73,
    image: 'https://randomuser.me/api/portraits/men/78.jpg',
    name: 'Gary Walker',
    email: 'j.skhu@internet.com',
    phone: '278726176370',
    date: '2003-10-21',
    organization: 'Tech Innovators Inc.',
    tags: 1,
    lastUpdated: '1 month ago',
  },
  {
    id: 74,
    image: 'https://randomuser.me/api/portraits/men/41.jpg',
    name: 'Charles Martinez',
    email: 'y.zbkvmpugo@internet.com',
    phone: '876406645967',
    date: '1984-04-02',
    organization: 'NextGen Technologies',
    tags: 3,
    lastUpdated: '2 months ago',
  },
  {
    id: 75,
    image: 'https://randomuser.me/api/portraits/men/61.jpg',
    name: 'Cynthia Harris',
    email: 'o.nwtjrrfwrr@internet.com',
    phone: '74865703275',
    date: '2016-04-15',
    organization: 'Visionary Labs',
    tags: 1,
    lastUpdated: '4 weeks ago',
  },
  {
    id: 76,
    image: 'https://randomuser.me/api/portraits/men/30.jpg',
    name: 'Betty Hall',
    email: 'o.erwi@internet.com',
    phone: '95559241205',
    date: '1980-08-06',
    organization: 'Global Solutions Ltd.',
    tags: 1,
    lastUpdated: '4 weeks ago',
  },
  {
    id: 77,
    image: 'https://randomuser.me/api/portraits/men/83.jpg',
    name: 'Ruth Rodriguez',
    email: 'o.ewi@internet.com',
    phone: '142775519583',
    date: '2023-05-21',
    organization: 'Stratosphere Networks',
    tags: 3,
    lastUpdated: '1 month ago',
  },
  {
    id: 78,
    image: 'https://randomuser.me/api/portraits/men/18.jpg',
    name: 'Christopher Miller',
    email: 'a.zvhjv@internet.com',
    phone: '86839412465',
    date: '1992-09-30',
    organization: 'Visionary Labs',
    tags: 3,
    lastUpdated: '5 days ago',
  },
  {
    id: 79,
    image: 'https://randomuser.me/api/portraits/men/67.jpg',
    name: 'Frank Brown',
    email: 'g.nohfg@internet.com',
    phone: '491336598984',
    date: '1996-06-11',
    organization: 'Apollo Digital Solutions',
    tags: 1,
    lastUpdated: '2 days ago',
  },
  {
    id: 80,
    image: 'https://randomuser.me/api/portraits/men/38.jpg',
    name: 'Jennifer Allen',
    email: 'o.pxrrwlfsjc@internet.com',
    phone: '13136803449',
    date: '2018-01-16',
    organization: 'Stratosphere Networks',
    tags: 1,
    lastUpdated: '4 weeks ago',
  },
  {
    id: 81,
    image: 'https://randomuser.me/api/portraits/men/99.jpg',
    name: 'Shirley Moore',
    email: 'i.yjbkyt@internet.com',
    phone: '145613351197',
    date: '1996-05-23',
    organization: 'Stratosphere Networks',
    tags: 1,
    lastUpdated: '1 month ago',
  },
  {
    id: 82,
    image: 'https://randomuser.me/api/portraits/men/90.jpg',
    name: 'Carol White',
    email: 'b.gxolco@internet.com',
    phone: '46191871328',
    date: '1975-09-10',
    organization: 'Tech Innovators Inc.',
    tags: 2,
    lastUpdated: '1 month ago',
  },
  {
    id: 83,
    image: 'https://randomuser.me/api/portraits/men/40.jpg',
    name: 'Ruth Clark',
    email: 'e.vulsktvx@internet.com',
    phone: '678282182798',
    date: '1984-08-08',
    organization: 'Tech Innovators Inc.',
    tags: 2,
    lastUpdated: '1 week ago',
  },
  {
    id: 84,
    image: 'https://randomuser.me/api/portraits/men/63.jpg',
    name: 'Eric Clark',
    email: 'v.wjcwbvcdq@internet.com',
    phone: '267630401879',
    date: '1990-11-17',
    organization: 'Cyberdyne Systems',
    tags: 2,
    lastUpdated: '2 months ago',
  },
  {
    id: 85,
    image: 'https://randomuser.me/api/portraits/men/48.jpg',
    name: 'Jose Wilson',
    email: 'e.ilikghrck@internet.com',
    phone: '687955430998',
    date: '1970-12-25',
    organization: 'Stratosphere Networks',
    tags: 1,
    lastUpdated: '6 days ago',
  },
  {
    id: 86,
    image: 'https://randomuser.me/api/portraits/men/60.jpg',
    name: 'Nancy Jones',
    email: 'l.qdfvqkbdoi@internet.com',
    phone: '88405840618',
    date: '2022-12-06',
    organization: 'Quantum Enterprises',
    tags: 2,
    lastUpdated: '2 days ago',
  },
  {
    id: 87,
    image: 'https://randomuser.me/api/portraits/men/94.jpg',
    name: 'Paul Martinez',
    email: 's.nss@internet.com',
    phone: '72112587348',
    date: '1991-07-20',
    organization: 'Stratosphere Networks',
    tags: 3,
    lastUpdated: '2 months ago',
  },
  {
    id: 88,
    image: 'https://randomuser.me/api/portraits/men/26.jpg',
    name: 'Paul Brown',
    email: 'j.ssxc@internet.com',
    phone: '485672522602',
    date: '2021-01-24',
    organization: 'Quantum Enterprises',
    tags: 2,
    lastUpdated: '6 days ago',
  },
  {
    id: 89,
    image: 'https://randomuser.me/api/portraits/men/97.jpg',
    name: 'Steven Robinson',
    email: 'h.ijnnc@internet.com',
    phone: '44394105068',
    date: '1972-12-13',
    organization: 'Stratosphere Networks',
    tags: 1,
    lastUpdated: '6 days ago',
  },
  {
    id: 90,
    image: 'https://randomuser.me/api/portraits/men/23.jpg',
    name: 'Jason Walker',
    email: 'n.auq@internet.com',
    phone: '22723587316',
    date: '1985-04-11',
    organization: 'Vertex Innovations',
    tags: 3,
    lastUpdated: '4 weeks ago',
  },
  {
    id: 91,
    image: 'https://randomuser.me/api/portraits/men/15.jpg',
    name: 'Brian Lewis',
    email: 'g.pwmm@internet.com',
    phone: '447283880599',
    date: '1993-09-14',
    organization: 'Cyberdyne Systems',
    tags: 3,
    lastUpdated: '5 days ago',
  },
  {
    id: 92,
    image: 'https://randomuser.me/api/portraits/men/28.jpg',
    name: 'Donald Perez',
    email: 'f.hndcj@internet.com',
    phone: '849597663975',
    date: '1984-05-17',
    organization: 'Stratosphere Networks',
    tags: 1,
    lastUpdated: '6 days ago',
  },
  {
    id: 93,
    image: 'https://randomuser.me/api/portraits/men/18.jpg',
    name: 'Barbara Thomas',
    email: 'i.dfewbql@internet.com',
    phone: '32998821865',
    date: '1988-03-17',
    organization: 'Global Solutions Ltd.',
    tags: 1,
    lastUpdated: '1 month ago',
  },
  {
    id: 94,
    image: 'https://randomuser.me/api/portraits/men/96.jpg',
    name: 'Richard White',
    email: 'g.cxwob@internet.com',
    phone: '79036855546',
    date: '1985-05-16',
    organization: 'Quantum Enterprises',
    tags: 1,
    lastUpdated: '3 weeks ago',
  },
  {
    id: 95,
    image: 'https://randomuser.me/api/portraits/men/56.jpg',
    name: 'John Garcia',
    email: 'm.hfpmosf@internet.com',
    phone: '39309418983',
    date: '2002-08-07',
    organization: 'Tech Innovators Inc.',
    tags: 3,
    lastUpdated: '4 weeks ago',
  },
  {
    id: 96,
    image: 'https://randomuser.me/api/portraits/men/90.jpg',
    name: 'Jason Smith',
    email: 'i.ixbmag@internet.com',
    phone: '272905861824',
    date: '1971-12-25',
    organization: 'Quantum Enterprises',
    tags: 2,
    lastUpdated: '3 weeks ago',
  },
  {
    id: 97,
    image: 'https://randomuser.me/api/portraits/men/11.jpg',
    name: 'Dorothy Lee',
    email: 't.woyjwyj@internet.com',
    phone: '68561592503',
    date: '1989-05-07',
    organization: 'Apollo Digital Solutions',
    tags: 1,
    lastUpdated: '2 months ago',
  },
  {
    id: 98,
    image: 'https://randomuser.me/api/portraits/men/56.jpg',
    name: 'Michael Garcia',
    email: 't.duychff@internet.com',
    phone: '521649099296',
    date: '1976-07-13',
    organization: 'Visionary Labs',
    tags: 2,
    lastUpdated: '2 months ago',
  },
  {
    id: 99,
    image: 'https://randomuser.me/api/portraits/men/94.jpg',
    name: 'Karen Thompson',
    email: 'c.xkuzlygfn@internet.com',
    phone: '673226696581',
    date: '2017-03-19',
    organization: 'Cyberdyne Systems',
    tags: 1,
    lastUpdated: '4 weeks ago',
  },
  {
    id: 100,
    image: 'https://randomuser.me/api/portraits/men/69.jpg',
    name: 'Cynthia Johnson',
    email: 'k.pvyvvq@internet.com',
    phone: '237350485987',
    date: '1983-08-06',
    organization: 'NextGen Technologies',
    tags: 1,
    lastUpdated: '2 days ago',
  },
];
