export const data = [
  {
    id: 1,
    name: 'Margaret Rodriguez',
    type: 2,
    code: 'HFK07710',
    priority: 1,
    date: '1979-02-20',
    subject: 'User access problem',
    image: 'https://randomuser.me/api/portraits/men/65.jpg',
  },
  {
    id: 2,
    name: 'George Walker',
    type: 3,
    code: 'WON37407',
    priority: 2,
    date: '2004-09-22',
    subject: 'Data breach',
    image: 'https://randomuser.me/api/portraits/men/13.jpg',
  },
  {
    id: 3,
    name: 'Jeffrey Lopez',
    type: 3,
    code: 'FCB79132',
    priority: 1,
    date: '2003-08-14',
    subject: 'Database connection error',
    image: 'https://randomuser.me/api/portraits/men/19.jpg',
  },
  {
    id: 4,
    name: 'Robert Lee',
    type: 1,
    code: 'KEW30398',
    priority: 1,
    date: '2023-11-07',
    subject: 'User access problem',
    image: 'https://randomuser.me/api/portraits/men/17.jpg',
  },
  {
    id: 5,
    name: 'Susan Hall',
    type: 3,
    code: 'FGF83444',
    priority: 1,
    date: '2001-10-26',
    subject: 'Firewall configuration issue',
    image: 'https://randomuser.me/api/portraits/men/81.jpg',
  },
  {
    id: 6,
    name: 'Sandra Clark',
    type: 1,
    code: 'QOG87575',
    priority: 2,
    date: '2000-09-13',
    subject: 'User access problem',
    image: 'https://randomuser.me/api/portraits/men/86.jpg',
  },
  {
    id: 7,
    name: 'Mark Rodriguez',
    type: 2,
    code: 'OIU14756',
    priority: 2,
    date: '1975-01-05',
    subject: 'Software update issue',
    image: 'https://randomuser.me/api/portraits/men/70.jpg',
  },
  {
    id: 8,
    name: 'Sarah Martinez',
    type: 2,
    code: 'DUG30506',
    priority: 3,
    date: '2022-07-26',
    subject: 'System performance degradation',
    image: 'https://randomuser.me/api/portraits/men/58.jpg',
  },
  {
    id: 9,
    name: 'Shirley Clark',
    type: 2,
    code: 'PTB30419',
    priority: 1,
    date: '1980-12-14',
    subject: 'Network latency',
    image: 'https://randomuser.me/api/portraits/men/40.jpg',
  },
  {
    id: 10,
    name: 'Linda Hall',
    type: 3,
    code: 'NPC06219',
    priority: 1,
    date: '1975-08-13',
    subject: 'Email delivery failure',
    image: 'https://randomuser.me/api/portraits/men/34.jpg',
  },
  {
    id: 11,
    name: 'Jennifer Jones',
    type: 1,
    code: 'BJS32114',
    priority: 1,
    date: '2023-11-26',
    subject: 'Email delivery failure',
    image: 'https://randomuser.me/api/portraits/men/60.jpg',
  },
  {
    id: 12,
    name: 'Donna Clark',
    type: 1,
    code: 'WCM52946',
    priority: 2,
    date: '1997-01-02',
    subject: 'Data breach',
    image: 'https://randomuser.me/api/portraits/men/79.jpg',
  },
  {
    id: 13,
    name: 'Kevin Williams',
    type: 1,
    code: 'SFX46822',
    priority: 1,
    date: '1975-08-15',
    subject: 'Database connection error',
    image: 'https://randomuser.me/api/portraits/men/77.jpg',
  },
  {
    id: 14,
    name: 'Lisa Martinez',
    type: 2,
    code: 'LKH52575',
    priority: 1,
    date: '2013-04-19',
    subject: 'Firewall configuration issue',
    image: 'https://randomuser.me/api/portraits/men/36.jpg',
  },
  {
    id: 15,
    name: 'Edward Robinson',
    type: 2,
    code: 'LTK37159',
    priority: 1,
    date: '1970-02-26',
    subject: 'Database connection error',
    image: 'https://randomuser.me/api/portraits/men/45.jpg',
  },
  {
    id: 16,
    name: 'Maria Robinson',
    type: 1,
    code: 'YTY51641',
    priority: 3,
    date: '2000-04-06',
    subject: 'Data breach',
    image: 'https://randomuser.me/api/portraits/men/67.jpg',
  },
  {
    id: 17,
    name: 'Timothy Hernandez',
    type: 2,
    code: 'VBY73588',
    priority: 2,
    date: '1996-08-16',
    subject: 'Disk space full',
    image: 'https://randomuser.me/api/portraits/men/49.jpg',
  },
  {
    id: 18,
    name: 'Sharon Hernandez',
    type: 1,
    code: 'WPE27098',
    priority: 3,
    date: '1978-12-28',
    subject: 'Disk space full',
    image: 'https://randomuser.me/api/portraits/men/80.jpg',
  },
  {
    id: 19,
    name: 'Helen Lopez',
    type: 3,
    code: 'YOH74662',
    priority: 2,
    date: '2002-11-23',
    subject: 'Data breach',
    image: 'https://randomuser.me/api/portraits/men/81.jpg',
  },
  {
    id: 20,
    name: 'Ronald Perez',
    type: 1,
    code: 'GIA92600',
    priority: 3,
    date: '1987-10-13',
    subject: 'User access problem',
    image: 'https://randomuser.me/api/portraits/men/28.jpg',
  },
  {
    id: 21,
    name: 'Frank Lee',
    type: 1,
    code: 'RTD37066',
    priority: 3,
    date: '2005-05-16',
    subject: 'Disk space full',
    image: 'https://randomuser.me/api/portraits/men/9.jpg',
  },
  {
    id: 22,
    name: 'Mark Clark',
    type: 1,
    code: 'ISN54068',
    priority: 1,
    date: '1980-03-30',
    subject: 'Server down',
    image: 'https://randomuser.me/api/portraits/men/60.jpg',
  },
  {
    id: 23,
    name: 'Daniel Davis',
    type: 1,
    code: 'WJG49844',
    priority: 2,
    date: '2005-03-02',
    subject: 'Firewall configuration issue',
    image: 'https://randomuser.me/api/portraits/men/30.jpg',
  },
  {
    id: 24,
    name: 'Ruth Thompson',
    type: 2,
    code: 'MEE22271',
    priority: 3,
    date: '1987-08-17',
    subject: 'Email delivery failure',
    image: 'https://randomuser.me/api/portraits/men/30.jpg',
  },
  {
    id: 25,
    name: 'Laura Clark',
    type: 3,
    code: 'OOY34442',
    priority: 1,
    date: '1994-09-13',
    subject: 'Firewall configuration issue',
    image: 'https://randomuser.me/api/portraits/men/35.jpg',
  },
  {
    id: 26,
    name: 'Jason Martinez',
    type: 3,
    code: 'MFX03647',
    priority: 2,
    date: '1972-06-14',
    subject: 'Software update issue',
    image: 'https://randomuser.me/api/portraits/men/15.jpg',
  },
  {
    id: 27,
    name: 'George Martin',
    type: 2,
    code: 'ITA54788',
    priority: 2,
    date: '2011-06-27',
    subject: 'Network latency',
    image: 'https://randomuser.me/api/portraits/men/37.jpg',
  },
  {
    id: 28,
    name: 'Timothy Johnson',
    type: 3,
    code: 'RMA23828',
    priority: 3,
    date: '1972-05-27',
    subject: 'Network latency',
    image: 'https://randomuser.me/api/portraits/men/40.jpg',
  },
  {
    id: 29,
    name: 'Sandra Gonzalez',
    type: 2,
    code: 'UMH07877',
    priority: 3,
    date: '1990-04-14',
    subject: 'Network latency',
    image: 'https://randomuser.me/api/portraits/men/10.jpg',
  },
  {
    id: 30,
    name: 'Sandra Walker',
    type: 3,
    code: 'AIQ60581',
    priority: 2,
    date: '2017-07-23',
    subject: 'System performance degradation',
    image: 'https://randomuser.me/api/portraits/men/47.jpg',
  },
  {
    id: 31,
    name: 'Paul Taylor',
    type: 3,
    code: 'MLV89374',
    priority: 3,
    date: '1995-01-07',
    subject: 'Database connection error',
    image: 'https://randomuser.me/api/portraits/men/11.jpg',
  },
  {
    id: 32,
    name: 'Deborah Miller',
    type: 3,
    code: 'ZKP55363',
    priority: 3,
    date: '1995-02-04',
    subject: 'User access problem',
    image: 'https://randomuser.me/api/portraits/men/19.jpg',
  },
  {
    id: 33,
    name: 'Patricia Thompson',
    type: 3,
    code: 'FXL92684',
    priority: 1,
    date: '1977-02-08',
    subject: 'Firewall configuration issue',
    image: 'https://randomuser.me/api/portraits/men/67.jpg',
  },
  {
    id: 34,
    name: 'Nancy Johnson',
    type: 3,
    code: 'ZNU03757',
    priority: 1,
    date: '2009-01-30',
    subject: 'Software update issue',
    image: 'https://randomuser.me/api/portraits/men/54.jpg',
  },
  {
    id: 35,
    name: 'John Brown',
    type: 1,
    code: 'OQE56167',
    priority: 2,
    date: '1985-02-04',
    subject: 'User access problem',
    image: 'https://randomuser.me/api/portraits/men/81.jpg',
  },
  {
    id: 36,
    name: 'Kenneth Young',
    type: 1,
    code: 'MUZ78784',
    priority: 3,
    date: '1984-12-15',
    subject: 'Database connection error',
    image: 'https://randomuser.me/api/portraits/men/65.jpg',
  },
  {
    id: 37,
    name: 'Helen Lewis',
    type: 1,
    code: 'CEB58360',
    priority: 1,
    date: '1977-12-28',
    subject: 'Email delivery failure',
    image: 'https://randomuser.me/api/portraits/men/52.jpg',
  },
  {
    id: 38,
    name: 'Mark Thomas',
    type: 1,
    code: 'ZZU42343',
    priority: 3,
    date: '1978-12-20',
    subject: 'Data breach',
    image: 'https://randomuser.me/api/portraits/men/88.jpg',
  },
  {
    id: 39,
    name: 'Donald Wilson',
    type: 3,
    code: 'HZF12406',
    priority: 1,
    date: '1997-04-14',
    subject: 'Disk space full',
    image: 'https://randomuser.me/api/portraits/men/77.jpg',
  },
  {
    id: 40,
    name: 'Michael Brown',
    type: 2,
    code: 'LGP55324',
    priority: 3,
    date: '1985-03-02',
    subject: 'Software update issue',
    image: 'https://randomuser.me/api/portraits/men/88.jpg',
  },
  {
    id: 41,
    name: 'Nancy Walker',
    type: 3,
    code: 'YEZ81610',
    priority: 3,
    date: '2017-08-08',
    subject: 'Email delivery failure',
    image: 'https://randomuser.me/api/portraits/men/88.jpg',
  },
  {
    id: 42,
    name: 'Elizabeth Lopez',
    type: 1,
    code: 'VAR42837',
    priority: 3,
    date: '2003-03-19',
    subject: 'Database connection error',
    image: 'https://randomuser.me/api/portraits/men/19.jpg',
  },
  {
    id: 43,
    name: 'Carol Perez',
    type: 1,
    code: 'VTM61401',
    priority: 3,
    date: '1976-02-29',
    subject: 'Database connection error',
    image: 'https://randomuser.me/api/portraits/men/10.jpg',
  },
  {
    id: 44,
    name: 'Sarah Williams',
    type: 1,
    code: 'KBY02081',
    priority: 1,
    date: '2006-09-14',
    subject: 'User access problem',
    image: 'https://randomuser.me/api/portraits/men/64.jpg',
  },
  {
    id: 45,
    name: 'Jennifer Thomas',
    type: 3,
    code: 'RPO34886',
    priority: 2,
    date: '2019-08-14',
    subject: 'User access problem',
    image: 'https://randomuser.me/api/portraits/men/47.jpg',
  },
  {
    id: 46,
    name: 'Eric Miller',
    type: 1,
    code: 'KXA91706',
    priority: 1,
    date: '1972-06-23',
    subject: 'Email delivery failure',
    image: 'https://randomuser.me/api/portraits/men/49.jpg',
  },
  {
    id: 47,
    name: 'Sandra Davis',
    type: 1,
    code: 'QPB37310',
    priority: 1,
    date: '1991-03-08',
    subject: 'Database connection error',
    image: 'https://randomuser.me/api/portraits/men/59.jpg',
  },
  {
    id: 48,
    name: 'Ronald Jones',
    type: 3,
    code: 'ZLE32154',
    priority: 2,
    date: '2017-03-29',
    subject: 'Email delivery failure',
    image: 'https://randomuser.me/api/portraits/men/70.jpg',
  },
  {
    id: 49,
    name: 'Gary Miller',
    type: 3,
    code: 'REL91695',
    priority: 1,
    date: '1995-11-15',
    subject: 'System performance degradation',
    image: 'https://randomuser.me/api/portraits/men/59.jpg',
  },
  {
    id: 50,
    name: 'Donna Lewis',
    type: 1,
    code: 'TOM60320',
    priority: 2,
    date: '2011-05-23',
    subject: 'Network latency',
    image: 'https://randomuser.me/api/portraits/men/41.jpg',
  },
  {
    id: 51,
    name: 'Kevin Clark',
    type: 2,
    code: 'VPC68905',
    priority: 3,
    date: '1972-11-26',
    subject: 'User access problem',
    image: 'https://randomuser.me/api/portraits/men/31.jpg',
  },
  {
    id: 52,
    name: 'Larry Harris',
    type: 1,
    code: 'RHU70308',
    priority: 1,
    date: '1979-09-03',
    subject: 'User access problem',
    image: 'https://randomuser.me/api/portraits/men/37.jpg',
  },
  {
    id: 53,
    name: 'Maria Williams',
    type: 1,
    code: 'QZG09428',
    priority: 1,
    date: '1994-09-23',
    subject: 'Firewall configuration issue',
    image: 'https://randomuser.me/api/portraits/men/11.jpg',
  },
  {
    id: 54,
    name: 'William Johnson',
    type: 3,
    code: 'BMB15211',
    priority: 1,
    date: '2005-09-18',
    subject: 'System performance degradation',
    image: 'https://randomuser.me/api/portraits/men/61.jpg',
  },
  {
    id: 55,
    name: 'Carol Wilson',
    type: 1,
    code: 'KPJ33144',
    priority: 2,
    date: '2012-02-12',
    subject: 'Server down',
    image: 'https://randomuser.me/api/portraits/men/8.jpg',
  },
  {
    id: 56,
    name: 'Dorothy Lewis',
    type: 2,
    code: 'RMP46386',
    priority: 3,
    date: '2018-09-23',
    subject: 'Server down',
    image: 'https://randomuser.me/api/portraits/men/41.jpg',
  },
  {
    id: 57,
    name: 'Patricia Robinson',
    type: 3,
    code: 'WJJ22997',
    priority: 1,
    date: '1980-08-05',
    subject: 'Email delivery failure',
    image: 'https://randomuser.me/api/portraits/men/59.jpg',
  },
  {
    id: 58,
    name: 'John Martin',
    type: 2,
    code: 'ETS30048',
    priority: 3,
    date: '1973-05-01',
    subject: 'Software update issue',
    image: 'https://randomuser.me/api/portraits/men/42.jpg',
  },
  {
    id: 59,
    name: 'Kimberly Johnson',
    type: 3,
    code: 'NUK75269',
    priority: 2,
    date: '2019-07-17',
    subject: 'Server down',
    image: 'https://randomuser.me/api/portraits/men/67.jpg',
  },
  {
    id: 60,
    name: 'Maria Hall',
    type: 1,
    code: 'IKP25483',
    priority: 1,
    date: '2009-06-27',
    subject: 'Email delivery failure',
    image: 'https://randomuser.me/api/portraits/men/23.jpg',
  },
  {
    id: 61,
    name: 'Joseph Martin',
    type: 3,
    code: 'BIO38059',
    priority: 1,
    date: '1986-06-05',
    subject: 'Data breach',
    image: 'https://randomuser.me/api/portraits/men/74.jpg',
  },
  {
    id: 62,
    name: 'Jennifer White',
    type: 1,
    code: 'UHK17677',
    priority: 1,
    date: '2023-06-07',
    subject: 'User access problem',
    image: 'https://randomuser.me/api/portraits/men/75.jpg',
  },
  {
    id: 63,
    name: 'Linda Hernandez',
    type: 1,
    code: 'YNE33395',
    priority: 3,
    date: '1986-02-08',
    subject: 'Firewall configuration issue',
    image: 'https://randomuser.me/api/portraits/men/32.jpg',
  },
  {
    id: 64,
    name: 'Jennifer Thomas',
    type: 2,
    code: 'XMO81832',
    priority: 2,
    date: '1983-10-31',
    subject: 'Firewall configuration issue',
    image: 'https://randomuser.me/api/portraits/men/33.jpg',
  },
  {
    id: 65,
    name: 'Timothy Thompson',
    type: 3,
    code: 'XAB93939',
    priority: 2,
    date: '2011-06-05',
    subject: 'Firewall configuration issue',
    image: 'https://randomuser.me/api/portraits/men/37.jpg',
  },
  {
    id: 66,
    name: 'Nancy Thompson',
    type: 2,
    code: 'LFA55192',
    priority: 1,
    date: '1979-10-18',
    subject: 'Software update issue',
    image: 'https://randomuser.me/api/portraits/men/25.jpg',
  },
  {
    id: 67,
    name: 'Sharon Lopez',
    type: 3,
    code: 'GNT76357',
    priority: 1,
    date: '1981-04-21',
    subject: 'Firewall configuration issue',
    image: 'https://randomuser.me/api/portraits/men/54.jpg',
  },
  {
    id: 68,
    name: 'William Harris',
    type: 2,
    code: 'TLW07086',
    priority: 3,
    date: '2012-04-25',
    subject: 'Network latency',
    image: 'https://randomuser.me/api/portraits/men/70.jpg',
  },
  {
    id: 69,
    name: 'Brenda Rodriguez',
    type: 1,
    code: 'GZC58080',
    priority: 1,
    date: '2008-04-12',
    subject: 'Data breach',
    image: 'https://randomuser.me/api/portraits/men/35.jpg',
  },
  {
    id: 70,
    name: 'Jennifer Jones',
    type: 2,
    code: 'OWP86672',
    priority: 1,
    date: '1987-07-08',
    subject: 'Email delivery failure',
    image: 'https://randomuser.me/api/portraits/men/57.jpg',
  },
  {
    id: 71,
    name: 'Helen White',
    type: 3,
    code: 'OVG12172',
    priority: 3,
    date: '2008-10-25',
    subject: 'Software update issue',
    image: 'https://randomuser.me/api/portraits/men/73.jpg',
  },
  {
    id: 72,
    name: 'Deborah Lewis',
    type: 1,
    code: 'GMD04823',
    priority: 3,
    date: '2011-03-26',
    subject: 'Server down',
    image: 'https://randomuser.me/api/portraits/men/96.jpg',
  },
  {
    id: 73,
    name: 'Angela Wilson',
    type: 1,
    code: 'HRC14206',
    priority: 1,
    date: '2006-12-22',
    subject: 'Disk space full',
    image: 'https://randomuser.me/api/portraits/men/37.jpg',
  },
  {
    id: 74,
    name: 'Mary Taylor',
    type: 3,
    code: 'WHO26520',
    priority: 3,
    date: '1972-02-13',
    subject: 'Server down',
    image: 'https://randomuser.me/api/portraits/men/6.jpg',
  },
  {
    id: 75,
    name: 'Ruth Moore',
    type: 1,
    code: 'IVB60579',
    priority: 2,
    date: '2003-12-19',
    subject: 'Data breach',
    image: 'https://randomuser.me/api/portraits/men/9.jpg',
  },
  {
    id: 76,
    name: 'Amy Johnson',
    type: 1,
    code: 'NRK58639',
    priority: 3,
    date: '2019-02-03',
    subject: 'Server down',
    image: 'https://randomuser.me/api/portraits/men/16.jpg',
  },
  {
    id: 77,
    name: 'Jason Brown',
    type: 2,
    code: 'RRR59692',
    priority: 1,
    date: '1984-02-08',
    subject: 'System performance degradation',
    image: 'https://randomuser.me/api/portraits/men/78.jpg',
  },
  {
    id: 78,
    name: 'Brian Johnson',
    type: 1,
    code: 'QUI93284',
    priority: 2,
    date: '1972-11-04',
    subject: 'Server down',
    image: 'https://randomuser.me/api/portraits/men/54.jpg',
  },
  {
    id: 79,
    name: 'Margaret Walker',
    type: 3,
    code: 'UXT53003',
    priority: 3,
    date: '1977-05-02',
    subject: 'System performance degradation',
    image: 'https://randomuser.me/api/portraits/men/31.jpg',
  },
  {
    id: 80,
    name: 'Nancy Rodriguez',
    type: 1,
    code: 'GZT14025',
    priority: 3,
    date: '2019-04-16',
    subject: 'User access problem',
    image: 'https://randomuser.me/api/portraits/men/91.jpg',
  },
  {
    id: 81,
    name: 'Paul Thompson',
    type: 1,
    code: 'VHJ34691',
    priority: 2,
    date: '1970-06-23',
    subject: 'Disk space full',
    image: 'https://randomuser.me/api/portraits/men/52.jpg',
  },
  {
    id: 82,
    name: 'Susan Johnson',
    type: 3,
    code: 'ALY20971',
    priority: 3,
    date: '1982-05-04',
    subject: 'Data breach',
    image: 'https://randomuser.me/api/portraits/men/42.jpg',
  },
  {
    id: 83,
    name: 'Daniel Martinez',
    type: 3,
    code: 'BSX53827',
    priority: 1,
    date: '1992-05-28',
    subject: 'Software update issue',
    image: 'https://randomuser.me/api/portraits/men/47.jpg',
  },
  {
    id: 84,
    name: 'Scott Jones',
    type: 3,
    code: 'ELA68867',
    priority: 1,
    date: '1994-12-07',
    subject: 'Email delivery failure',
    image: 'https://randomuser.me/api/portraits/men/52.jpg',
  },
  {
    id: 85,
    name: 'Maria Robinson',
    type: 2,
    code: 'TDP93992',
    priority: 1,
    date: '1995-10-30',
    subject: 'Software update issue',
    image: 'https://randomuser.me/api/portraits/men/91.jpg',
  },
  {
    id: 86,
    name: 'Sharon Thompson',
    type: 1,
    code: 'YAK66750',
    priority: 2,
    date: '1991-10-17',
    subject: 'Disk space full',
    image: 'https://randomuser.me/api/portraits/men/35.jpg',
  },
  {
    id: 87,
    name: 'Cynthia Martinez',
    type: 3,
    code: 'HKJ06569',
    priority: 3,
    date: '2007-12-20',
    subject: 'Data breach',
    image: 'https://randomuser.me/api/portraits/men/30.jpg',
  },
  {
    id: 88,
    name: 'Amy Hall',
    type: 1,
    code: 'QJZ88162',
    priority: 3,
    date: '1975-09-24',
    subject: 'Network latency',
    image: 'https://randomuser.me/api/portraits/men/23.jpg',
  },
  {
    id: 89,
    name: 'Steven Hall',
    type: 3,
    code: 'SUD51962',
    priority: 3,
    date: '1975-12-06',
    subject: 'Server down',
    image: 'https://randomuser.me/api/portraits/men/17.jpg',
  },
  {
    id: 90,
    name: 'Paul Martinez',
    type: 2,
    code: 'OSW29883',
    priority: 1,
    date: '1975-07-11',
    subject: 'Disk space full',
    image: 'https://randomuser.me/api/portraits/men/91.jpg',
  },
  {
    id: 91,
    name: 'Deborah Jones',
    type: 3,
    code: 'NFL51834',
    priority: 3,
    date: '1982-10-05',
    subject: 'User access problem',
    image: 'https://randomuser.me/api/portraits/men/74.jpg',
  },
  {
    id: 92,
    name: 'Nancy Walker',
    type: 1,
    code: 'UDR30235',
    priority: 1,
    date: '2022-12-08',
    subject: 'Firewall configuration issue',
    image: 'https://randomuser.me/api/portraits/men/66.jpg',
  },
  {
    id: 93,
    name: 'Brian Martin',
    type: 3,
    code: 'LNP73507',
    priority: 3,
    date: '2021-07-09',
    subject: 'Firewall configuration issue',
    image: 'https://randomuser.me/api/portraits/men/68.jpg',
  },
  {
    id: 94,
    name: 'Carol Hernandez',
    type: 3,
    code: 'MPQ80870',
    priority: 1,
    date: '1982-06-20',
    subject: 'Email delivery failure',
    image: 'https://randomuser.me/api/portraits/men/91.jpg',
  },
  {
    id: 95,
    name: 'Sandra Lopez',
    type: 1,
    code: 'ZDP41810',
    priority: 3,
    date: '2007-01-18',
    subject: 'Email delivery failure',
    image: 'https://randomuser.me/api/portraits/men/54.jpg',
  },
  {
    id: 96,
    name: 'Frank Anderson',
    type: 1,
    code: 'DOJ17354',
    priority: 3,
    date: '2016-08-17',
    subject: 'Disk space full',
    image: 'https://randomuser.me/api/portraits/men/14.jpg',
  },
  {
    id: 97,
    name: 'Brian Miller',
    type: 2,
    code: 'KYU15474',
    priority: 1,
    date: '1974-05-06',
    subject: 'User access problem',
    image: 'https://randomuser.me/api/portraits/men/99.jpg',
  },
  {
    id: 98,
    name: 'Anna Thompson',
    type: 1,
    code: 'PXE15988',
    priority: 2,
    date: '1995-06-30',
    subject: 'System performance degradation',
    image: 'https://randomuser.me/api/portraits/men/82.jpg',
  },
  {
    id: 99,
    name: 'Elizabeth Anderson',
    type: 1,
    code: 'TZN25326',
    priority: 3,
    date: '2017-05-04',
    subject: 'System performance degradation',
    image: 'https://randomuser.me/api/portraits/men/82.jpg',
  },
  {
    id: 100,
    name: 'Sarah Lopez',
    type: 2,
    code: 'AMP57293',
    priority: 3,
    date: '1970-12-22',
    subject: 'Database connection error',
    image: 'https://randomuser.me/api/portraits/men/53.jpg',
  },
];

export const dataConversation = [
  {
    title: 'Hanif',
    desc: '11:12 AM. Via Email',
    content: 'Apakah kamu bisa membantu saya?',
  },
  {
    title: 'Elwin',
    desc: '11:12 AM. Via Whatsapp',
    content: 'Iya Hanif, apa yang bisa saya bantu?',
  },
];
